python manage.py makemigrations
Traceback (most recent call last):
  File "/home/eter/.local/share/Trash/files/eter-projectv1.0/eter_backend/manage.py", line 22, in <module>
    main()
  File "/home/eter/.local/share/Trash/files/eter-projectv1.0/eter_backend/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/contrib/admin/__init__.py", line 52, in autodiscover
    autodiscover_modules("admin", register_to=site)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/eter/.local/share/Trash/files/eter-projectv1.0/eter_backend/apps/core/admin.py", line 6, in <module>
    from .models import (
ImportError: cannot import name 'FicheVerificationPointage' from 'apps.core.models' (/home/eter/.local/share/Trash/files/eter-projectv1.0/eter_backend/apps/core/models.py)